# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-mentions
#  - jekyll-include-cache

# Site settings
title: "dimasyuwono"
description: > # this means to ignore newlines until "email:"
   I need to start somewhere, right ? I have to.

email: dimazyuwono@gmail.com
#blog logo
logo: "/assets/images/back.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Dimas Yuwono'
author: 'Dimas Yuwono'
author_image: "/assets/images/back.jpg"

paginate:	5

url: "https://dimazyuwono.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dimazyuwono'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dimazyuwono
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dimazyuwono
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
